# Generated by Django 3.2.6 on 2021-10-11 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(auto_created=True, max_length=250, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(auto_created=True, default='', max_length=250, verbose_name='Страна')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='destination/list', verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Название')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Описание')),
                ('category', models.PositiveSmallIntegerField(null=True, verbose_name='Категория')),
                ('is_repair', models.BooleanField(default=False, verbose_name='Недавно отремонтирован')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/list', verbose_name='Загрузить изображение')),
                ('city', models.ForeignKey(auto_created=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.city', verbose_name='Город')),
                ('country', models.ForeignKey(auto_created=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='Цена за ночь')),
                ('category', models.CharField(choices=[('эконом', 'эконом'), ('комфорт', 'комфорт'), ('люкс', 'люкс'), ('полулюкс', 'полулюкс')], default='комфорт', max_length=10, null=True, verbose_name='Тип номера')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='rooms/list', verbose_name='Фотография номера')),
                ('is_booking', models.BooleanField(default=False, verbose_name='Забронирована')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(null=True, verbose_name='Оценка пользователя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created', models.DateField(verbose_name='Дата отзыва')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ManyToManyField(related_name='services', to='hotels.Service', verbose_name='Сервис'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityes', to='hotels.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
